# Generated by Django 5.1.7 on 2025-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
